CREATE DATABASE IF NOT EXISTS `2212500462`;
USE `2212500462`;

CREATE TABLE IF NOT EXISTS contact (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contact VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contact VARCHAR(100)
);
